### ISSUE TITLE
WP Shortcode Civi 4.7

### ISSUE THREAD

**Issue by danaskallman** [JMAConsulting/biz.jmaconsulting.grantapplications#124] opened 2016-04-05 14:09 UTC
I tested the latest version of this extension with WP 4.4.2 and CiviCRM 4.7.4 and it's working well on the CiviCRM parts. The only part I can't get to work is the shortcode. I checked permissions and they all seem to be correct for profile fields to be viewed. When I add a shortocde to a page and go there is says:

`You do not have permission to access this content.`

Even when logged in as site administrator. I can see and submit the application with the direct link from the CiviCRM `Grant Application (Live)` link in the Grants Dashboard.

Are there specific permissions needed or is there something else I am missing?

**Comment by JoeMurray** [comment] 2016-04-05 15:13
Could you provide a bit more detail on the fields in the profile? Also, there are now permissions on financial type in core, so could you check which financial type was being used for the grant application, and whether the user had permissions to view and edit it?

**Comment by danaskallman** [comment] 2016-04-05 15:39
I am just using default profile fields now, so First Name, Last Name, Employer and Email, plus amount requested from Grants.

In the Grant Application I don't see where I set the Financial Type. Currently there is no financial type for grant. I can create a new financial type, but how do I then assign to the grant application?

**Comment by Edzelopez** [comment] 2016-04-06 02:01
HI @danaskallman,

Could you please make sure you have the 'Submit Grant Applications online' permission? It's a new core permission that has been added via our extension. Also, did you replace the files under includes with the ones under shortcode-wp folder?

**Comment by kcristiano** [comment] 2016-04-06 11:21
@Edzelopez Just looking at the last comment - does this extension still require replacement of Core files?

**Comment by Edzelopez** [comment] 2016-04-06 11:25
Unfortunately, yes, for Wordpress. There is just one core file which needs to be replaced, which is under the shortcode-wp directory. 
The file in CiviCRM that needs to be replaced is wp-content/plugins/civicrm/includes/civicrm.shortcodes.php

**Comment by kcristiano** [comment] 2016-04-06 20:29
I know that I spoke with Joe about this.   For me that makes this extension unusable for WP.

**Comment by JoeMurray** [comment] 2016-04-06 20:32
Agreed. We need to use a method that avoids any overwriting of files. Can you remind us here what the issue was with getting core team to make it possible for an extension to define new shortcodes?

**Comment by kcristiano** [comment] 2016-04-06 22:10
Joe I had thought that Coleman was addressing this.  Did this https://github.com/civicrm/civicrm-wordpress/commit/411e1385a805fa89946d0e6ef979aca427a82be2  help at all?

**Comment by Edzelopez** [comment] 2016-04-07 05:34
@kcristiano that did help, we were able to remove the shortcode selection code that was overridden [https://github.com/JMAConsulting/biz.jmaconsulting.grantapplications/commit/4cb13adc2a9690ab95b7ed2094939924f2c8c46b](here)

The part that remains in core though is stuff like [https://github.com/civicrm/civicrm-wordpress/blob/master/includes/civicrm.shortcodes.php#L681](this). Unless there is a way to somehow extend this function (I'm not that familiar with how stuff works in wordpress), we have no other alternative other than overriding.

**Comment by kcristiano** [comment] 2016-04-07 11:08
It would be helpful to open a JIRA issue and tag it with WordPress.   We
should look at how this calss could be extended or at least allow extension
authors to filter the list of defined shortcodes.   Christian Wach
refactored this and we can reach out to him to take a look.

**Comment by SandyEllingson** [comment] 2017-07-26 13:22
I am having a similar problem. I am using WP version 4.8, Civicrm Ver 4.7.16 and Grant Applications version 1.5.1.  When I try to use the shortcode I get the same error about not having permissions, even when logged in as administrator and the error about the shortcodes: Warning: Invalid argument supplied for foreach() in /home/som/www/www/wp-content/plugins/civicrm/includes/civicrm.shortcodes.php on line 269. I have tested to make sure that no other plugins or themes are causing the error. Is there an update or something else I can do to resolve?

**Comment by Edzelopez** [comment] 2017-07-26 13:30
Hi @SandyEllingson,

Just making sure you have replaced the civicrm.shortcodes.php file with the one under shortcode-wp/includes in this extension. Also, you will need the  'Submit Grant Applications online' permission for your administrator role checked.

**Comment by SandyEllingson** [comment] 2017-07-26 13:54
I will try that. I hadn't done anything since the post was almost a year old and this is my first time using GitHuB so I wanted to make sure that anything I grabbed was correct.

**Comment by SandyEllingson** [comment] 2017-07-26 15:07
Thank you that seemed to work.

**Comment by JoeMurray** [comment] 2018-09-24 16:38
@Edzelopez ping

**Comment by JoeMurray** [comment] 2018-09-24 16:40
Closing as duplicate of https://github.com/JMAConsulting/biz.jmaconsulting.grantapplications/issues/134

**Closed by JoeMurray** 2018-09-24 16:40 UTC
