### ISSUE TITLE
Fatal error when used with logging

### ISSUE THREAD

**Issue by shawnholt** [JMAConsulting/biz.jmaconsulting.grantapplications#109] opened 2015-06-30 12:19 UTC
I have seen this before with extensions that use external database tables as the log table is not created properly. will try to disable/re-enable or create log manually.

Jun 30 08:14:56  [info] $backTrace = #0 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Error.php(235): CRM_Core_Error::backtrace("backTrace", TRUE)
#1 [internal function](): CRM_Core_Error::handle(Object(DB_Error))
#2 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/packages/PEAR.php(931): call_user_func((Array:2), Object(DB_Error))
#3 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/packages/DB.php(976): PEAR_Error->PEAR_Error("DB Error: no such table", -18, 16, (Array:2), "INSERT INTO civicrm_grant_app_page (title , intro_text , footer_text , grant_...")
#4 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/packages/PEAR.php(564): DB_Error->DB_Error(-18, 16, (Array:2), "INSERT INTO civicrm_grant_app_page (title , intro_text , footer_text , grant_...")
#5 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/packages/DB/common.php(1905): PEAR->raiseError(NULL, -18, NULL, NULL, "INSERT INTO civicrm_grant_app_page (title , intro_text , footer_text , grant_...", "DB_Error", TRUE)
#6 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/packages/DB/mysql.php(899): DB_common->raiseError(-18, NULL, NULL, NULL, "1146 ** Table 'xxxxx_civi.log_civicrm_grant_app_page' doesn't exist")
#7 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/packages/DB/mysql.php(328): DB_mysql->mysqlRaiseError()
#8 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/packages/DB/common.php(1216): DB_mysql->simpleQuery("INSERT INTO civicrm_grant_app_page (title , intro_text , footer_text , grant_...")
#9 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/packages/DB/DataObject.php(2442): DB_common->query("INSERT INTO civicrm_grant_app_page (title , intro_text , footer_text , grant_...")
#10 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/packages/DB/DataObject.php(1060): DB_DataObject->_query("INSERT INTO civicrm_grant_app_page (title , intro_text , footer_text , grant_...")
#11 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/DAO.php(450): DB_DataObject->insert()
#12 /home/xxxxx/public_html/wp-content/plugins/files/civicrm/extensions/biz.jmaconsulting.grantapplications/CRM/Grant/BAO/GrantApplicationPage.php(53): CRM_Core_DAO->save()
#13 /home/xxxxx/public_html/wp-content/plugins/files/civicrm/extensions/biz.jmaconsulting.grantapplications/CRM/Grant/Form/GrantPage/Settings.php(239): CRM_Grant_BAO_GrantApplicationPage::create((Array:20))
#14 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Form.php(345): CRM_Grant_Form_GrantPage_Settings->postProcess()
#15 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/StateMachine.php(164): CRM_Core_Form->mainProcess()
#16 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/QuickForm/Action/Next.php(61): CRM_Core_StateMachine->perform(Object(CRM_Grant_Form_GrantPage_Settings), "next", "Next")
#17 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Grant_Form_GrantPage_Settings), "next")
#18 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Grant_Form_GrantPage_Settings), "next")
#19 /home/xxxxx/public_html/wp-content/plugins/files/civicrm/extensions/biz.jmaconsulting.grantapplications/CRM/Core/Controller.php(359): HTML_QuickForm_Page->handle("next")
#20 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(312): CRM_Core_Controller->run((Array:4), NULL)
#21 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:14))
#22 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:4))
#23 /home/xxxxx/public_html/wp-content/plugins/civicrm/civicrm.php(1189): CRM_Core_Invoke::invoke((Array:4))
#24 [internal function](): CiviCRM_For_WordPress->invoke("")
#25 /home/xxxxx/public_html/wp-includes/plugin.php(496): call_user_func_array((Array:2), (Array:1))
#26 /home/xxxxx/public_html/wp-admin/admin.php(226): do_action("toplevel_page_CiviCRM")

**Comment by JoeMurray** [comment] 2015-06-30 18:53
What were you doing when the error occurred? In particular, what was the URL?

**Comment by shawnholt** [comment] 2015-06-30 19:06
creating grant application.

**Comment by JoeMurray** [comment] 2015-06-30 19:17
It appears the software is not properly installed as a needed table is missing. What is the current version of grant application pages extension installed, and what is the history of its installation and upgrade on this instance?

**Comment by shawnholt** [comment] 2015-07-01 18:42
Sorry @JoeMurray I do not have a clear history, however, I disabled via backend database (backend was not usable.) turrned off logging, re-enabled, turned on logging and it worked fine.  I saw this same issue once before (in drupal) with the mailchimp module - https://github.com/veda-consulting/uk.co.vedaconsulting.mailchimp/issues/74

**Comment by JoeMurray** [comment] 2015-07-16 17:56
Closing as unreproducible and likely due to odd install/upgrade path.

**Closed by JoeMurray** 2015-07-16 17:56 UTC
